feature/CS-405
CubeStatistica/Website pull request #99
Opened 2022-12-09 18:37 UTC by SuneetaDevi

Re-design Navbar of Website

No errors
No warnings
Website is working fine

2022-12-10 00:57 UTC, FaizanKhalidMohsin approved these changes

2022-12-10 01:00 UTC, FaizanKhalidMohsin requested changes
@SuneetaDevi there are some merge conflicts, could you take a look at them. Let me know if you need help resolving them.

2022-12-10 08:07 UTC, SuneetaDevi commented
@FaizanKhalidMohsin  conflicts has been resolved kindly review and approve

2022-12-14 17:01 UTC, FaizanKhalidMohsin approved these changes

2022-12-14 17:01 UTC, merged